jobs:
- job:
  displayName: 'Build iOS app'
  pool:
    name: Hosted macOS
    demands:
    - xcode
    - Xamarin.iOS
    - msbuild
  steps:
  - bash: echo "Hello from macOS"

- job:
  displayName: 'Build Android app'
  pool:
    name: Hosted macOS
    demands:
    - xcode
    - Xamarin.iOS
    - msbuild
  steps:
  - bash: echo "Hello from Android"

- job:
  displayName: 'Build Windows app'
  pool:
    name: Hosted VS2017
    demands:
    - msbuild
    - visualstudio
  steps:
  - script: |
     echo Hello from Windows

