variables:
  BuildConfiguration: 'Release'
  iOS-Certificate-Password: ''

jobs:
- job:
  displayName: 'Build iOS app'
  pool:
    name: Hosted macOS
    demands:
    - xcode
    - Xamarin.iOS
    - msbuild
  steps:
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: 'Mobile/**/*.csproj'
      feedsToUse: 'select'
      versioningScheme: 'off'

  - task: qetza.replacetokens.replacetokens-task.replacetokens@3
    inputs:
      rootDirectory: 'Mobile/ContosoFieldService.Core/Helpers'
      targetFiles: 'Constants.cs'
      encoding: 'auto'
      writeBOM: true
      actionOnMissing: 'warn'
      keepToken: false
      tokenPrefix: '__'
      tokenSuffix: '__'

  - task: ios-bundle-version@1
    inputs:
      sourcePath: 'Mobile/iOS/Info.plist'
      versionCodeOption: 'buildid'
      versionCode: '$(Build.BuildId)'
      printFile: false

  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: 'Xamarin-Shared-In-House-Cert-PrivateKey.p12'
      certPwd: '$(iOS-Certificate-Password)'
      keychain: 'temp'

  - task: InstallAppleProvisioningProfile@1
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: 'Contoso_Maintenance_InHouse.mobileprovision'

  - task: XamariniOS@2
    inputs:
      solutionFile: 'Mobile/iOS/ContosoFieldService.iOS.csproj'
      configuration: '$(BuildConfiguration)'
      packageApp: true
      runNugetRestore: false
      args: '/p:OutputPath="$(Build.ArtifactStagingDirectory)/iOS"'
      signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
      signingProvisioningProfileID: '$(APPLE_PROV_PROFILE_UUID)'

  - task: XamariniOS@2
    inputs:
      solutionFile: 'Mobile/iOS/ContosoFieldService.iOS.csproj'
      configuration: 'Test Cloud'
      packageApp: true
      runNugetRestore: false
      args: '/p:OutputPath="$(Build.ArtifactStagingDirectory)/iOS/TestCloud"'
      signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
      signingProvisioningProfileID: '$(APPLE_PROV_PROFILE_UUID)'

  - task: MSBuild@1
    inputs:
      solution: 'Mobile/UITests/ContosoFieldService.UITests.csproj'
      configuration: '$(BuildConfiguration)'
      msbuildArguments: '/p:OutputPath="$(Build.ArtifactStagingDirectory)/iOS/TestCloud"'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.Repository.LocalPath)/packages/Xamarin.UITest.2.2.6/'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/iOS/TestCloud/packages/Xamarin.UITest.2.2.6/'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'iOS'
      publishLocation: 'Container'

- job:
  displayName: 'Build Android app'
  pool:
    name: Hosted macOS
    demands:
    - xcode
    - Xamarin.iOS
    - msbuild
  steps:
  - bash: echo "Hello from Android"


- job:
  displayName: 'Build Windows app'
  pool:
    name: Hosted VS2017
    demands:
    - msbuild
    - visualstudio
  steps: 
  - task: VSBuild@1
    displayName: 'Build UWP project'
    inputs:
      solution: Mobile/ContosoFieldService.UWP/ContosoFieldService.UWP.csproj
      configuration: '$(BuildConfiguration)'
